namespace Lyra.HostedService
{
    using System.Collections.Generic;

    public static class SettingsBuilder
    {
        public static Dictionary<string, string> BuildDictionary(LyraHostedServiceSettings settings)
        {
            var dictionary = new Dictionary<string, string>
            {
                {"Auth:InternalStsUrl", settings.InternalStsUrl.ToString()},
                {"Auth:ClientId", settings.ClientId},
                {"Auth:ClientSecret", settings.ClientSecret},

                {"CloudFrontUrl", settings.CloudFrontUrl },

                {"TenantSettings:default:FeatureFlags:BitcoinEnabled", "false"},
                {"TenantSettings:default:FeatureFlags:EthereumEnabled", "false"},
                {"TenantSettings:default:FeatureFlags:BitcoinCashEnabled", "false"},
                {"TenantSettings:default:FeatureFlags:LitecoinEnabled", "false"},
                {"TenantSettings:default:FeatureFlags:RippleEnabled", "false"},
                {"TenantSettings:default:FeatureFlags:CoffeeEnabled", "false"},
                {"TenantSettings:default:FeatureFlags:SoulEnabled", "false"},
                {"TenantSettings:default:FeatureFlags:NoticeEnabled", "false"},
                {"TenantSettings:default:FeatureFlags:TrapEnabled", "false"},
                {"TenantSettings:default:FeatureFlags:PorcupineEnabled", "false"},
                {"TenantSettings:default:FeatureFlags:DieEnabled", "false"},

                {"TenantSettings:dingo:FeatureFlags:BitcoinEnabled", "true"},
                {"TenantSettings:dingo:FeatureFlags:EthereumEnabled", "true"},
                {"TenantSettings:dingo:FeatureFlags:BitcoinCashEnabled", "true"},
                {"TenantSettings:dingo:FeatureFlags:LitecoinEnabled", "true"},
                {"TenantSettings:dingo:FeatureFlags:RippleEnabled", "true"},

                {"TenantSettings:dolphin:FeatureFlags:BitcoinEnabled", "true"},
                {"TenantSettings:dolphin:FeatureFlags:EthereumEnabled", "true"},
                {"TenantSettings:dolphin:FeatureFlags:BitcoinCashEnabled", "true"},
                {"TenantSettings:dolphin:FeatureFlags:LitecoinEnabled", "true"},
                {"TenantSettings:dolphin:FeatureFlags:CoffeeEnabled", "true"},
                {"TenantSettings:dolphin:FeatureFlags:SoulEnabled", "true"},
                {"TenantSettings:dolphin:FeatureFlags:NoticeEnabled", "true"},
                {"TenantSettings:dolphin:FeatureFlags:TrapEnabled", "true"},
                {"TenantSettings:dolphin:FeatureFlags:PorcupineEnabled", "true"},
                {"TenantSettings:dolphin:FeatureFlags:DieEnabled", "true"},

                {"Products:1:Id", "currency.crypto.BTC" },
                {"Products:1:Category", "Crypto" },
                {"Products:1:Code", "BTC" },
                {"Products:1:Name", "Bitcoin" },
                {"Products:1:Icon", "Bitcoin" },
                {"Products:1:Card", "bitcoin/bitcoin-card.png" },
                {"Products:1:Cover", "bitcoin/bitcoin-cover.png" },
                {"Products:1:Color", "#2D3778" },

                {"Products:2:Id", "currency.crypto.ETH"},
                {"Products:2:Category", "Crypto" },
                {"Products:2:Code", "ETH" },
                {"Products:2:Name", "Ethereum" },
                {"Products:2:Icon", "Ethereum" },
                {"Products:2:Card", "ethereum/ethereum-card.png" },
                {"Products:2:Cover", "ethereum/ethereum-cover.png" },
                {"Products:2:Color", "#6DAAB0"},

                {"Products:3:Id", "currency.crypto.LTC"},
                {"Products:3:Category", "Crypto"},
                {"Products:3:Code", "LTC"},
                {"Products:3:Name", "Litecoin"},
                {"Products:3:Icon", "Litecoin"},
                {"Products:3:Card", "litecoin/litecoin-card.png"},
                {"Products:3:Cover", "litecoin/litecoin-cover.png"},
                {"Products:3:Color", "#6A4C69"},

                {"Products:4:Id", "currency.crypto.BCH"},
                {"Products:4:Category", "Crypto"},
                {"Products:4:Code", "BCH"},
                {"Products:4:Name", "Bitcoin Cash"},
                {"Products:4:Icon", "BitcoinCash"},
                {"Products:4:Card", "bitcoin-cash/bitcoin-cash-card.png"},
                {"Products:4:Cover", "bitcoin-cash/bitcoin-cash-cover.png"},
                {"Products:4:Color", "#4A5490"},

                {"Products:5:Id", "token.lykke.COFFEE"},
                {"Products:5:Category", "Auction"},
                {"Products:5:Code", "COFFEE"},
                {"Products:5:Name", "Coffee and TV"},
                {"Products:5:Icon", "MyLyCI"},
                {"Products:5:Card", "coffee/coffee-card.png"},
                {"Products:5:Cover", "coffee/coffee-cover.png"},
                {"Products:5:Color", "#6DAAB0"},
                {"Products:5:ArtistName", "Blur"},
                {"Products:5:AllTimeEarnings", "1458.25"},
                {"Products:5:UnitsAvailable", "500"},
                {"Products:5:AuctionCloseDate", "Mon, 5 Jul 2021 16:19:43 GMT"},
                {"Products:5:Description", "“Coffee & TV” is a 1999 song by the British rock band Blur. It was written by the band's guitarist, Graham Coxon, who also sang lead vocals, rather than frontman Damon Albarn. The song appears on Blur's sixth studio album, 13 and was the second single released from the album. The lyrics describe Coxon's struggle with alcoholism and the song's video, featuring a sentient milk carton searching for Coxon, won several awards. Commercially, “Coffee & TV” reached No. 11 in the United Kingdom and No. 26 in Ireland. It was a major hit in Iceland, where it peaked at No. 2 in September 1999. The song was recorded, along with the rest of the material for 13 in late 1998, with producer William Orbit. Coxon wrote the song about his struggle from alcoholism, and how he would unwind by watching television over a cup of coffee instead, and writing songs. This experience also contributed to his first solo album, The Sky Is Too High. The song's musical style is an anomaly in comparison with the rest of 13, appearing similar to Blur's earlier, Britpop days. Despite featuring heavy guitar distortion and feedback during the instrumental break, major characteristics of 13, the track generally features subdued, calm lyrics and vocals. The edit of the singles cuts off the instrumental part after the fade out and runs about 40 seconds shorter than the album version. This instrumental part is a hidden track, which, though officially untitled, is known as “Coffee & TV Exitlude”." },

                {"Products:6:Id", "token.lykke.NOTICE"},
                {"Products:6:Category", "Auction"},
                {"Products:6:Code", "NOTICE"},
                {"Products:6:Name", "Notice Me"},
                {"Products:6:Icon", "MyLyCI"},
                {"Products:6:Card", "notice/notice-card.png"},
                {"Products:6:Cover", "notice/notice-cover.png"},
                {"Products:6:Color", "#6DAAB0"},
                {"Products:6:ArtistName", "Fana Hues"},
                {"Products:6:AllTimeEarnings", "1328.45"},
                {"Products:6:UnitsAvailable", "500"},
                {"Products:6:AuctionCloseDate", "Mon, 5 Jul 2021 17:19:43 GMT"},
                {"Products:6:Description", "When singer-songwriter Fana Hues was a child, illness took away her voice for almost five years. “I had scarlet fever, tonsillitis, and strep throat at the same time,” recalls the 25-year-old from Pasadena, CA, about the years she spent yearning to sing—years her mother, a dancer and healer, spent concocting natural medicines and elixirs that would eventually restore her voice." },
   
                {"Products:7:Id", "token.lykke.TRAP"},
                {"Products:7:Category", "Auction"},
                {"Products:7:Code", "TRAP"},
                {"Products:7:Name", "Trap Phone"},
                {"Products:7:Icon", "MyLyCI"},
                {"Products:7:Card", "trap/trap-card.png"},
                {"Products:7:Cover", "trap/trap-cover.png"},
                {"Products:7:Color", "#6DAAB0"},
                {"Products:7:ArtistName", "Berwyn"},
                {"Products:7:AllTimeEarnings", "1458.25"},
                {"Products:7:UnitsAvailable", "500"},
                {"Products:7:AuctionCloseDate", "Mon, 12 Apr 2021 12:19:43 GMT"},
                {"Products:7:Description", "Poignantly posed lyrics with an emotionally evocative delivery and a powerful sense of storytelling are what set BERWYN apart from other artists in East London right now. He evokes such a strong sense of emotion in his music that makes the lyrics hit hard like the final blow of a prize winning fight and his expressive delivery only enhances this further. He’s already demonstrated this single GLORY which is one of the best solo debuts out there right now and today he’s dropped a contender for song of the year in TRAP PHONE." },

                {"Products:8:Id", "token.lykke.PORCUPINE"},
                {"Products:8:Category", "Auction"},
                {"Products:8:Code", "PORCUPINE"},
                {"Products:8:Name", "Porcupine"},
                {"Products:8:Icon", "MyLyCI"},
                {"Products:8:Card", "porcupine/porcupine-card.png"},
                {"Products:8:Cover", "porcupine/porcupine-cover.png"},
                {"Products:8:Color", "#6DAAB0"},
                {"Products:8:ArtistName", "Molly Payton"},
                {"Products:8:AllTimeEarnings", "1458.25"},
                {"Products:8:UnitsAvailable", "500"},
                {"Products:8:AuctionCloseDate", "Mon, 12 Apr 2021 12:19:43 GMT"},
                {"Products:8:Description", "A lot of Molly Payton's tracks have been written in the tube, when the night is over and booze courses her veins. “It’s where I do my best writing,” she laughs. “When I’m absolutely hammered and angry at someone.” It figures: her music is drenched in melancholy, laced with yearning vocals and cutting lyrics about boys who read too much Kerouac and wish they lived in 1972. Still, she has her reservations about the habit. “It’s not good,” she jokes, “how as a musician you capitalize off heartbreak. I’m at a point now where if I have a bad experience with a guy I’m like, 'Sweet, thanks mate! Great song.”" },

                {"Products:9:Id", "token.lykke.DIE"},
                {"Products:9:Category", "Auction"},
                {"Products:9:Code", "DIE"},
                {"Products:9:Name", "Don't Die"},
                {"Products:9:Icon", "MyLyCI"},
                {"Products:9:Card", "die/die-card.png"},
                {"Products:9:Cover", "die/die-cover.png"},
                {"Products:9:Color", "#6DAAB0"},
                {"Products:9:ArtistName", "HVN"},
                {"Products:9:AllTimeEarnings", "1458.25"},
                {"Products:9:UnitsAvailable", "500"},
                {"Products:9:AuctionCloseDate", "Mon, 12 Apr 2021 12:19:43 GMT"},
                {"Products:9:Description", "HVN coined the movement's name Don’t Die in 2015 when he was diagnosed with sickle cell anemia, a disease he still battles with unto this day. HVN's resilience served to not only be the motivation he needed, but that so many others in Houston did as well. Infusing vintage punk rock with modern day rap, remaining solely for the youth, and incorporating all genres of music, the Don’t Die movement has authentically become Houston’s best kept secret." },

                {"Products:10:Id", "token.lykke.SOUL" },
                {"Products:10:Category", "CopyrightToken" },
                {"Products:10:Code", "SOUL" },
                {"Products:10:Name", "Soul Meets Body" },
                {"Products:10:Icon", "MyLyCI" },
                {"Products:10:Card", "soul/soul-card.png" },
                {"Products:10:Cover", "soul/soul-cover.png" },
                {"Products:10:Color", "#4A5490" },
                {"Products:10:ArtistName", "Death Cab for Cutie" },
                {"Products:10:AlbumName", "Album Hues · 2020" },
                {"Products:10:Description", "“Soul Meets Body” is a song by indie rock band Death Cab for Cutie, the first single from their fifth album, Plans, released on October 10, 2005. It was their debut single released on Atlantic Records, and it has become the band's second highest charting single in the United States. The song peaked at number 5 on the U.S. Billboard Hot Modern Rock Tracks chart. The song is certified as gold by the Recording Industry Association of America for shipping over 500,000 copies. Before it had been officially released the song was leaked onto the internet by an unknown source, to which guitarist Chris Walla stated positively in response, “I love it. The more anarchy we can give to the record industry, the better.” “Soul Meets Body” charted for 14 weeks in the Hot Modern Rock Tracks chart, peaking at number 5, and 18 weeks in the Billboard Hot 100, where it peaked at number 60." },

                {"Products:11:Id", "currency.crypto.XRP" },
                {"Products:11:Category", "Crypto" },
                {"Products:11:Code", "XRP" },
                {"Products:11:Name", "Ripple" },
                {"Products:11:Icon", "Ripple" },
                {"Products:11:Card", "ripple/ripple-card.png" },
                {"Products:11:Cover", "ripple/ripple-cover.png" },
                {"Products:11:Color", "#8B6C8A" },

                {"Products:12:Id", "currency.simple.EUR" },
                {"Products:12:Category", "SIMPLE" },
                {"Products:12:Code", "XRP" },
                {"Products:12:Name", "RippleSimple" },
                {"Products:12:Icon", "Ripple" },
                {"Products:12:Card", "simple/ripple-card.png" },
                {"Products:12:Cover", "simple/ripple-cover.png" },
                {"Products:12:Color", "#8G6C8A" },

                {"Products:13:Id", "currency.fiat.EUR" },
                {"Products:13:Category", "FIAT" },
                {"Products:13:Code", "XRP" },
                {"Products:13:Name", "RippleFiat" },
                {"Products:13:Icon", "Ripple" },
                {"Products:13:Card", "fiat/ripple-card.png" },
                {"Products:13:Cover", "fiat/ripple-cover.png" },
                {"Products:13:Color", "#8B6C6A" },
            };

            return dictionary;
        }
    }
}